stages:
  - build
  - deploy-gcp

build_images:
  stage: build
  iamge: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t joaosilvaaa/kubernetes-projeto2-dio:1.0 app/.
    - docker push joaosilvaaa/kubernetes-projeto2-dio:1.0

deploy_gcp:
  stage: deply_gcp

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./kubernetes-projeto2-dio/ && sudo git clone https://gitlab.com/denilsonbonatti/kubernetes-projeto2-dio.git && cd kubernetes-projeto2-dio && sudo chmod +x ./script.sh && ./script.sh"